source "http://rubygems.org"
# Add dependencies required to use your gem here.
# Example:
#   gem "activesupport", ">= 2.3.5"

# Add dependencies to develop your gem here.
# Include everything needed to run rake, tests, features, etc.

gem "rdoc"
gem "rake"
gem "rest-client", "~> 1.6.6"
gem "json"

group :development do
  gem "shoulda", ">= 0"
  gem "rdoc"
  gem "bundler"
  gem "jeweler"
  gem "simplecov", ">= 0"
  gem "rr"
end
