# encoding: utf-8

require 'rubygems'
require 'bundler'
begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end
require 'rake'

require 'jeweler'
Jeweler::Tasks.new do |gem|
  # gem is a Gem::Specification... see http://docs.rubygems.org/read/chapter/20 for more options
  gem.name = "ooyala-v2-api"
  gem.homepage = "https://github.com/ooyala/api-sdks"
  gem.license = "MIT"
  gem.summary = %Q{Ooyala's API SDK}
  gem.description = %Q{Contains the necessary mehtods to communicate with the Ooyala's API.}
  gem.email = "jose@ooyala.com"
  gem.authors = ["Ooyala"]
  # dependencies defined in Gemfile
  # dependencies defined in Gemfile
  gem.add_dependency('json')
  gem.add_dependency('rest-client', "~> 1.6.6")
end
Jeweler::RubygemsDotOrgTasks.new

require 'rake/testtask'
Rake::TestTask.new(:test) do |test|
  test.libs << 'lib' << 'test'
  test.pattern = 'test/**/test_*.rb'
  test.verbose = true
end

task :default => :test

require 'rdoc/task'
Rake::RDocTask.new do |rdoc|
  version = File.exist?('VERSION') ? File.read('VERSION') : ""

  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = "ooyala-sdk #{version}"
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end
